package dev.omesh.glyphtoys.glyph

import java.io.File
import kotlin.math.roundToInt
import kotlin.test.Test
import org.junit.Assume.assumeTrue

/**
 * Regenerates the toy picker thumbnails.
 *
 * Nothing's stock toys show an actual dot matrix in the picker. A smooth vector icon sits there
 * looking like it belongs to a different app, so previews are rasterised through the same
 * [MatrixCanvas] the toys draw with and emitted as one dot per LED.
 *
 * Skipped on normal runs. To regenerate after changing a toy's look:
 *
 * ```
 * ./gradlew testDebugUnitTest --tests '*PreviewGeneratorTest*' -DgeneratePreviews=true
 * ```
 *
 * The art here mirrors each toy's `draw`. Keep them in step — it is a thumbnail, so a small
 * drift is survivable, but a preview showing something the toy never renders is not.
 */
class PreviewGeneratorTest {

    private val geometry = MatrixGeometry.PHONE_4A_PRO

    @Test
    fun `regenerate toy previews`() {
        assumeTrue("set -DgeneratePreviews=true to regenerate", System.getProperty("generatePreviews") != null)

        write("toy_charge", MatrixCanvas(geometry).apply {
            val c = (geometry.size - 1) / 2f
            val r = geometry.size / 2f - 1.5f
            ring(c, c, r, 1f, 0.12f)
            arc(c, c, r, 1f, sweep = 0.7f)
            disc(c, c, r * 0.18f, 0.85f)
        })

        write("toy_album", MatrixCanvas(geometry).apply {
            val c = (geometry.size - 1) / 2f
            // Stand-in for a cover: concentric bands, so the thumbnail reads as an image rather
            // than as an icon.
            disc(c, c, 5.5f, 0.30f)
            ring(c, c, 4.0f, 1.5f, 0.70f)
            ring(c, c, 2.0f, 1.5f, 1.00f)
            disc(c, c, 0.8f, 0.15f)
        })
    }

    /** One `<path>` per brightness bucket, each holding every dot at that level. */
    private fun write(name: String, canvas: MatrixCanvas) {
        // gamma = 1 on purpose. The usual encoding exists to linearise an LED's PWM; a thumbnail
        // is drawn on a screen that already applies its own gamma, so encoding here would apply
        // it twice and render every preview too dark.
        val frame = canvas.toFrame(gamma = 1f, max = 255)
        val buckets = sortedMapOf<Int, StringBuilder>()

        for (y in 0 until geometry.size) for (x in 0 until geometry.size) {
            val v = frame[geometry.index(x, y)]
            if (v == 0) continue
            val bucket = ((v / 255f * BUCKETS).roundToInt()).coerceIn(1, BUCKETS)
            buckets.getOrPut(bucket) { StringBuilder() }.append(dot(x, y))
        }

        val paths = buckets.entries.joinToString("\n") { (bucket, data) ->
            """    <path
        android:fillColor="#FFFFFF"
        android:fillAlpha="${"%.3f".format(bucket.toFloat() / BUCKETS)}"
        android:pathData="${data.toString().trim()}" />"""
        }

        val xml = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by PreviewGeneratorTest. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="${geometry.size}"
    android:viewportHeight="${geometry.size}">
$paths
</vector>
"""
        val out = File("src/main/res/drawable/$name.xml")
        out.writeText(xml)
        println("wrote ${out.absolutePath} (${buckets.size} levels)")
    }

    /** A circle centred on the LED, drawn as two half-arcs. */
    private fun dot(x: Int, y: Int): String {
        val cx = x + 0.5f
        val cy = y + 0.5f
        val r = DOT_RADIUS
        val d = r * 2
        return "M$cx,$cy m-$r,0 a$r,$r 0 1,0 $d,0 a$r,$r 0 1,0 -$d,0 Z "
    }

    private companion object {
        const val BUCKETS = 6
        const val DOT_RADIUS = 0.38f
    }
}
